// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhKNahyFI_kQepGa9JaiBOInauplWsT6g',
    appId: '1:291023129716:android:6dade6b87f293bc9ddd521',
    messagingSenderId: '291023129716',
    projectId: 'gymup-app-935d8',
    storageBucket: 'gymup-app-935d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVuDTZ0Yh6NdnbN3K_sWg985nov6WESYo',
    appId: '1:291023129716:ios:c1a279ee75d19fe4ddd521',
    messagingSenderId: '291023129716',
    projectId: 'gymup-app-935d8',
    storageBucket: 'gymup-app-935d8.firebasestorage.app',
    iosBundleId: 'com.example.gymup',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5D3WBA0obKBEH7RZCYG5tt05sMCweilE',
    appId: '1:291023129716:web:85eb9f861ea71844ddd521',
    messagingSenderId: '291023129716',
    projectId: 'gymup-app-935d8',
    authDomain: 'gymup-app-935d8.firebaseapp.com',
    storageBucket: 'gymup-app-935d8.firebasestorage.app',
    measurementId: 'G-90WFF8VWYM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVuDTZ0Yh6NdnbN3K_sWg985nov6WESYo',
    appId: '1:291023129716:ios:c1a279ee75d19fe4ddd521',
    messagingSenderId: '291023129716',
    projectId: 'gymup-app-935d8',
    storageBucket: 'gymup-app-935d8.firebasestorage.app',
    iosBundleId: 'com.example.gymup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5D3WBA0obKBEH7RZCYG5tt05sMCweilE',
    appId: '1:291023129716:web:ad36d8f454594e04ddd521',
    messagingSenderId: '291023129716',
    projectId: 'gymup-app-935d8',
    authDomain: 'gymup-app-935d8.firebaseapp.com',
    storageBucket: 'gymup-app-935d8.firebasestorage.app',
    measurementId: 'G-PVF6JFE9HY',
  );

}