name: gymup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.2
  intl: ^0.19.0
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1

  http: ^1.2.1
  image_picker: ^1.1.2
  google_sign_in: ^6.2.2
  shared_preferences: ^2.2.2
  fl_chart: ^0.70.2
  app_links: ^6.0.0
  shimmer: ^3.0.0
  web: ^1.1.0
  share_plus: ^7.0.0
  mobile_scanner: ^6.0.0
  permission_handler: ^11.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/challenges/
    - assets/icons/auth/
    - assets/icons/nav/
    - assets/icons/ranking/
    - assets/icons/workouts/
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Bold.ttf
          weight: 700
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
